version: '3.7'

services:

  gobtest:
    build:
      context: src
      target: development
    container_name: gobtest
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      GOB_SHARED_DIR: /app/shared
      MANAGEMENT_API_HOST: http://gobmanagement:8001
      GOB_DATABASE_PORT_OVERRIDE: 5432
      GOB_DATABASE_HOST_OVERRIDE: database
    env_file: ./.env
    volumes:
      - gob-volume:/app/shared
      - ./src/gobtest:/app/gobtest
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config

networks:
  default:
    name: gob-network
    external: true

volumes:
  gob-volume:
    external: true
