version: '3.0'

services:

  gobtest:
    build: src
    container_name: gobtest
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001

networks:
  default:
    external:
      name: gob-network
