version: '3.7'

services:

  gobtest:
    build: src
    container_name: gobtest
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      GOB_SHARED_DIR: /app/shared
      MANAGEMENT_API_HOST: http://gobmanagement:8001
      GOB_DATABASE_PORT_OVERRIDE: 5432
      GOB_DATABASE_HOST_OVERRIDE: database
    env_file: ./.env
    volumes:
      - gob-volume:/app/shared

networks:
  default:
    name: gob-network
    external: true

volumes:
  gob-volume:
    external: true
