version: '3.0'

services:

  gobtest:
    build: src
    container_name: gobtest
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      MANAGEMENT_API_HOST: http://gobmanagement:8001
      ANALYSE_DATABASE_USER: gob
      ANALYSE_DATABASE_PASSWORD: insecure
      ANALYSE_DATABASE_HOST_OVERRIDE: analyse_database
      ANALYSE_DATABASE_PORT_OVERRIDE: 5432
      ANALYSE_DATABASE: gob_analyse
networks:
  default:
    external:
      name: gob-network
